### ISSUE TITLE
Multicore support on Posix

### ISSUE THREAD

**Issue by liyinbo** [TrampolineRTOS/trampoline#161]
Hi，guys，do you have plans to support multicore on Posix?

**Comment by jlbirccyn** [comment]
Hello @liyinbo

We discussed this with my colleagues some 3 or 4 years ago, but we didn't pursue it because we didn't have the time to devote to it. From memory, the main ideas were as follows:

- Each core is a posix thread and are created in the StartCore service and at start for core 0. An array indexed by the core ID stores the pthread_t for each core;
- Entry point is set to a different function than main. This function creates the core 0 thread and runs it with main;
- After creating core 0 thread, the main thread runs Viper, which is no longer in a separate process; That way it can target the cores using ```pthread_kill```;
- Spinlocks are emulated using pthread equivalency.

It would be a nice project for a Master student.

**Comment by liyinbo** [comment]
Thank you very much for your contributions. It seems that supporting Multi-core would require a change in the architecture of Viper, and there is a lot of work involved in this.I will close this issue.
