### ISSUE TITLE
Kind of cortex CPU

### ISSUE THREAD

**Issue by Koryphon** [TrampolineRTOS/trampoline#2]

**Comment by jlbirccyn** [comment]
Currently we compile with flag `-mcpu=cortex-m4` for cortex armv7. It is ok because both supported targets are cortex M4 (stm32f407 and mk20dx256). In the future we plan to support Arduino Due and Microsemi Smartfusion2 which are both cortex M3.

An alternate flag: `-march=armv7-m`could be used instead.

Dome tests should be done to verify there is no problem caused by this change
