### ISSUE TITLE
python build system does not run under python 3.x

### ISSUE THREAD

**Issue by mbriday** [TrampolineRTOS/trampoline#33]
The python build system is limited to python 2.x

**Comment by Snakeuh** [comment]
Made it "work" with python 3.* with this patch.

[0001-enhancement-Fixes-33.patch.txt](https://github.com/TrampolineRTOS/trampoline/files/248988/0001-enhancement-Fixes-33.patch.txt)

By "work", i mean it compiles and produces an usable binary, however terminationSemaphore.acquire() doesn't see that a job has finished (so that a specific file has finished its compilation) so I had to manually stop and launch again the scripts each time a sequence of files had finished their compilation. It may be due to this computer's python environment though (ArchLinux python 3.5.1).

**Comment by jlbirccyn** [comment]
Updated to the latest version of the script which is now compatible with Python 2 _and_ Python 3. If someone could check it is ok with Python 3 (I do not have Python 3 installed on my computer).

**Comment by Snakeuh** [comment]
Commit 7b22091 : Copied the modifications of makefile.py plus a minor change in generic_galgas_makefile.py support python3 goil's compilation. Minor change too for the generation of build.py. Everything seems to work fine

**Comment by jlbirccyn** [comment]
Do we consider this issue is fixed ?

**Comment by jlbirccyn** [comment]
FIxed in 2839a7a059914501f4bdf47ff9f7751f70a8514e
